src/Sveak/CynologyBundle/Entity/Dog.php
<?php

namespace Sveak\CynologyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Sveak\CynologyBundle\Entity\Repository\DogRepository")
 * @ORM\Table(name="dog")
 * @ORM\HasLifecycleCallbacks()
 */
class Dog
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    protected $name;

    /**
     * @ORM\ManyToOne(targetEntity="DogBreed", inversedBy="dogs")
     * @ORM\JoinColumn(name="breed_id", referencedColumnName="id", nullable=false)
     */
    protected $breed;

    /**
     * @var Trainer
     *
     * @ORM\ManyToOne(targetEntity="Trainer", inversedBy="dogs")
     * @ORM\JoinColumn(name="trainer_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $trainer;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $has_pedigree;

    /**
     * @ORM\Column(type="date")
     */
    protected $birthday;

    /**
     * @var string
     */
    protected $age;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    public function __construct()
    {
        $this->setCreated(new \DateTime());
        $this->setUpdated(new \DateTime());
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Dog
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get hasPedigree
     *
     * @return boolean
     */
    public function getHasPedigree()
    {
        return $this->has_pedigree;
    }

    /**
     * Set hasPedigree
     *
     * @param boolean $hasPedigree
     *
     * @return Dog
     */
    public function setHasPedigree($hasPedigree)
    {
        $this->has_pedigree = $hasPedigree;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Dog
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return Dog
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedValue()
    {
        $this->setUpdated(new \DateTime());
    }

    /**
     * Get breed
     *
     * @return \Sveak\CynologyBundle\Entity\DogBreed
     */
    public function getBreed()
    {
        return $this->breed;
    }

    /**
     * Set breed
     *
     * @param DogBreed $breed
     *
     * @return Dog
     */
    public function setBreed(DogBreed $breed = null)
    {
        $this->breed = $breed;

        return $this;
    }

    /**
     * Get trainer
     *
     * @return \Sveak\CynologyBundle\Entity\Trainer
     */
    public function getTrainer()
    {
        return $this->trainer;
    }

    /**
     * Set trainer
     *
     * @param Trainer $trainer
     *
     * @return Dog
     */
    public function setTrainer(Trainer $trainer = null)
    {
        $this->trainer = $trainer;

        return $this;
    }

    public function getTrainerName()
    {
        if (false === is_null($this->trainer))
            return $this->trainer->getLastname();
        else
            return 'No Trainer';
    }

    /**
     * @return string
     */
    public function getAge()
    {
        $ageTime = (time() - $this->getBirthday()->getTimestamp()) / 86400;

        if ($ageTime < 30) {
            $age = 'less than 1 months';
        } elseif ($ageTime <= 365) {
            $age = floor($ageTime / 30) . ' months';
        } else {
            $age = floor($ageTime / 365) . ' years';
        }

        return $age;
    }

    /**
     * Get birthday
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Set birthday
     *
     * @param \DateTime $birthday
     *
     * @return Dog
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;

        return $this;
    }
}

src/Sveak/CynologyBundle/Form/DogType.php
<?php

namespace Sveak\CynologyBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DogType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('has_pedigree', CheckboxType::class, array(
                'required' => false
            ))
            ->add('birthday', DateType::class)
            ->add('trainer', EntityType::class, array(
                'class' => 'Sveak\CynologyBundle\Entity\Trainer',
                'placeholder' => 'No Trainer',
                'required' => false
            ))
            ->add('breed');
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Sveak\CynologyBundle\Entity\Dog'
        ));
    }
}

src/Sveak/CynologyBundle/Controller/DogController.php
<?php

namespace Sveak\CynologyBundle\Controller;


use Sveak\CynologyBundle\Entity\Dog;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DogController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $dogs = $this->getDoctrine()
            ->getManager()
            ->getRepository('SveakCynologyBundle:Dog')->findAll();

        // Creating pagnination
        $paginator = $this->container->get('knp_paginator');
        $pagination = $paginator->paginate(
            $dogs,
            $this->container->get('request')->query->get('page', 1),
            $this->container->getParameter('sveak_cynology.dog.page.limit')
        );

        $form_builder = $this->createFormBuilder()->setMethod('DELETE');

        return $this->render('SveakCynologyBundle:Dog:index.html.twig', compact(
            'pagination',
            'form_builder'
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $dog = new Dog();
        $form = $this->createForm('Sveak\CynologyBundle\Form\DogType', $dog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($dog);
            $em->flush();

            return $this->redirectToRoute('sveak_cynology_dog_index');
        }

        return $this->render('SveakCynologyBundle:Dog:new.html.twig', array(
            'dog' => $dog,
            'form' => $form->createView(),
        ));
    }

    /**
     * @param Request $request
     * @param Dog $dog
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, Dog $dog)
    {
        $deleteForm = $this->createDeleteForm($dog);
        $editForm = $this->createForm('Sveak\CynologyBundle\Form\DogType', $dog);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($dog);
            $em->flush();

            return $this->redirectToRoute('sveak_cynology_dog_edit', array('id' => $dog->getId()));
        }

        return $this->render('SveakCynologyBundle:Dog:edit.html.twig', array(
            'dog' => $dog,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * @param Dog|null $dog
     * @return \Symfony\Component\Form\Form|\Symfony\Component\Form\FormInterface
     */
    private function createDeleteForm(Dog $dog = null)
    {
        $formBuilder = $this->createFormBuilder();

        if (false === is_null($dog))
            $formBuilder->setAction($this->generateUrl('sveak_cynology_dog_delete', array('id' => $dog->getId())));

        return $formBuilder->setMethod('DELETE')
            ->getForm();
    }

    /**
     * @param Request $request
     * @param Dog $dog
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, Dog $dog)
    {
        $form = $this->createDeleteForm($dog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($dog);
            $em->flush();
        }

        return $this->redirectToRoute('sveak_cynology_dog_index');
    }
}

src/Sveak/CynologyBundle/Resources/views/Dog/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('sveak_cynology_dog_index') }}" class="btn btn-primary pull-right">Back to the list</a>
    <h1>Dog edit</h1>

    {{ form_start(edit_form) }}
    {{ form_widget(edit_form) }}
    <input type="submit" value="Save" class="btn btn-primary pull-left"/>
    {{ form_end(edit_form) }}

    {{ form_start(delete_form) }}
    <input type="submit" value="Delete" class="btn btn-danger"
           onclick="if (!confirm('Are you sure you want to delete this dog? This action can not be canceled.')) return false;">
    {{ form_end(delete_form) }}
{% endblock %}

src/Sveak/CynologyBundle/Resources/views/Dog/index.html.twig
{% extends 'SveakCynologyBundle::layout.html.twig' %}

{% block body %}
    <a href="{{ path('sveak_cynology_dog_new') }}" class="btn btn-primary pull-right">Create</a>
    <h1>Dogs</h1>
    <table class="table">
        <thead>
        <tr>
            <th class="sortable">{{ knp_pagination_sortable(pagination, 'Name', 'd.name') }}</th>
            <th class="sortable">{{ knp_pagination_sortable(pagination, 'Breed', 'b.breed') }}</th>
            <th class="sortable sortable-revert">{{ knp_pagination_sortable(pagination, 'Age', 'd.birthday', {'defaultDirection': 'desc'}) }}</th>
            <th class="sortable">{{ knp_pagination_sortable(pagination, 'Has Pedigree', 'd.has_pedigree') }}</th>
            <th class="sortable">{{ knp_pagination_sortable(pagination, 'Trainer', 't.lastname') }}</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for dog in pagination %}
            {% set delete_form = form_builder.setAction(path('sveak_cynology_dog_delete', { 'id': dog.id })).getForm().createView() %}
            <tr>
                <td>{{ dog.name }}</td>
                <td>{{ dog.breed.breed }}</td>
                <td>{{ dog.age }}</td>
                <td><span class="glyphicon glyphicon-{{ dog.hasPedigree ? 'ok' : 'remove' }}"></span></td>
                <td>{{ dog.trainerName }}</td>
                <td class="text-right">
                    <a href="{{ path('sveak_cynology_dog_edit', { 'id': dog.id }) }}"
                    ><span class="glyphicon glyphicon-pencil"></span></a> &nbsp;
                    <a onclick="if (confirm('Are you sure you want to delete this dog? This action can not be canceled.'))
                            $(this).parent().find('form').submit(); return;" href="javascript:void(0)">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                    {{ form(delete_form) }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

src/Sveak/CynologyBundle/Resources/views/Dog/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('sveak_cynology_dog_index') }}" class="btn btn-primary pull-right">Back to the list</a>
    <h1>Dog creation</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Create" class="btn btn-primary pull-left"/>
    {{ form_end(form) }}
{% endblock %}